filter:
    excluded_paths:
        - tests/*
build:
    environment:
        php: 7.2
    cache:
        disabled:             false
        directories:
            - ~/.composer/cache
            - tmp/
            - vendor/
            - composer.lock
    dependencies:
        override:
            - composer self-update
            - composer install --no-interaction --dev --prefer-dist --ansi
    tests:
        override:
            - command: composer build
              coverage:
                  file: clover.xml
                  format: clover
