filter:
    excluded_paths:
        - tests/*
build:
    environment:
        php:
          version: 7.3
          pecl_extensions:
            - redis
            - memcached
            - apcu
    cache:
        disabled:             false
        directories:
            - ~/.composer/cache
            - tmp/
            - vendor/
            - composer.lock
    dependencies:
        override:
            - composer self-update
            - composer install --no-interaction --dev --prefer-dist --ansi
    tests:
        override:
            - command: composer build
              coverage:
                  file: clover.xml
                  format: php-clover

    nodes:
      php71:
        environment:
          php: 7.1

      php72:
        environment:
          php: 7.2

      php73:
        environment:
          php: 7.3
